### ISSUE TITLE
[Suggestion] Make the bracket viewing more compact

### ISSUE THREAD

**Issue by dakoslug** [dxprog/anime-bracket#4]
When you have many contestants, the bracket viewing is very hard to see.

Is it possible to make it more compact to avoid horizontal scrolling?

**Comment by dxprog** [comment]
This one is a bit tricky since the bracket size is exponential (or logarithmic in this case, I suppose). The only way to reduce the width would be to start cramming later rounds into the columns of other rounds, which could reduce readability. I'll give it some thought and see if maybe there's some other way of displaying it (being able to set how many rounds to display, for instance).

**Comment by dxprog** [comment]
Deployed.
